version:  '3'
services:
    notebook:
        build: .
        volumes:
            - ./notebooks:/usr/src/app
            - ./tmp:/tmp
        ports:
            - "8888:8888"
        container_name: notebook